run:
  timeout: 1m

linters-settings:
  gocyclo:
    min-complexity: 16

  goconst:
    min-len: 2
    min-occurrences: 2

  misspell:
    locale: US

  lll:
    line-length: 120

  funlen:
    lines: 80
    statements: 40

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - errcheck
    - funlen
    - forcetypeassert
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gocognit
    - gochecknoinits
    - ineffassign
    - ifshort
    - importas
    - lll
    - misspell
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - varcheck
    - wsl
    - whitespace


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo
        - lll

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.54.x # use the fixed version to not introduce new linters unexpectedly